name: deployment-on-gke

on:
  push:
    branches:
      - main

jobs:
  test-deployment-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd authentication && npm install && npm run test:ci

  test-deployment-orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci

  test-deployment-tickets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci

  test-deployment-payments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci

  deploy:
    needs:
      [
        test-deployment-auth,
        test-deployment-orders,
        test-deployment-tickets,
        test-deployment-payments,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt Google Cloud Service Account Key
        env:
          PASSPHRASE: ${{ secrets.GKE_SERVICE_ACCOUNT_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
          --output /tmp/gcp-key.json ./eventhive-gke-service-account-key.json.gpg

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: /tmp/gcp-key.json
          project_id: eventhive-dev

      - name: Install GKE gcloud auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate with Google Cloud using service account
        run: |
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project eventhive-dev
          gcloud container clusters get-credentials eventhive-dev --zone asia-south2-b

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Deploy to GKE using Skaffold
        run: skaffold run -f skaffold.yaml --default-repo us.gcr.io/eventhive-dev
