name: deployment-on-gke

on:
  workflow_run:
    workflows: ["tests-auth", "tests-orders", "tests-payments", "tests-tickets"]
    types:
      - completed

jobs:
  wait_for_tests_to_complete:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to complete
        id: check_test_workflow
        run: |
          echo "Checking for successful completion of all workflows..."

          # Define a list of workflow names
          WORKFLOWS=("tests-auth" "tests-orders" "tests-payments" "tests-tickets")
          SUCCESS=true

          # Loop through each workflow name and check its result
          for workflow in "${WORKFLOWS[@]}"; do
              if [[ "${{ github.event.workflow_run.workflow }}" == "$workflow" && "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
              echo "Workflow $workflow did not succeed."
              SUCCESS=false
              fi
          done

          if [[ "$SUCCESS" == "false" ]]; then
              exit 1
          fi

  deploy:
    needs: wait_for_tests_to_complete
    if: ${{ needs.wait_for_tests_to_complete.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt Google Cloud Service Account Key
        env:
          PASSPHRASE: ${{ secrets.GKE_SERVICE_ACCOUNT_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
          --output /tmp/gcp-key.json ./eventhive-gke-service-account-key.json.gpg

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: /tmp/gcp-key.json
          project_id: eventhive-dev

      - name: Authenticate with Google Cloud using service account
        run: |
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project eventhive-dev
          gcloud container clusters get-credentials eventhive-dev --zone asia-south2-b

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Deploy to GKE using Skaffold
        run: skaffold run -f skaffold.yaml --default-repo us.gcr.io/eventhive-dev
