name: run_all_tests

on:
  workflow_run:
    workflows:
      - "tests-auth"
      - "tests-orders"
      - "tests-payments"
      - "tests-tickets"
    types:
      - completed

jobs:
  check-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if all test workflows passed
        id: check-tests
        run: |
          echo "Test workflows summary:"
          echo "tests-auth: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'tests-auth' }}"
          echo "tests-orders: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'tests-orders' }}"
          echo "tests-payments: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'tests-payments' }}"
          echo "tests-tickets: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'tests-tickets' }}"

      - name: Trigger Deployment
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'tests-auth' && github.event.workflow_run.workflow == 'tests-orders' && github.event.workflow_run.workflow == 'tests-payments' && github.event.workflow_run.workflow == 'tests-tickets' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "All tests passed successfully. Proceeding to deployment..."
          gh workflow run deployment-on-gke.yml --ref main
