name: tests-auth

on:
  pull_request:
    paths:
      - "authentication/**"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd authentication && npm install && npm run test:ci
